[package]
name = "reddish"
version = "0.2.0"
edition = "2021"
description = """
A Rust utility library
"""
authors = ["Rogério Araújo <rogerio.araujo@mail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rodgeraraujo/reddish"
documentation = "https://docs.rs/reddish"
homepage = "https://reddish.github.io"
include = ["Cargo.toml", "src/", "LICENSE", "README.md"]

[feature]
default = ["array", "string"]
array = ["concat", "difference", "find_index", "find_last_index", "join"]
string = ["camel_case", "capitalize", "kebab_case", "snake_case", "title_case", "pad", "pad_end", "truncate"]

[dependencies]

[dev-dependencies]
